#!/usr/bin/env python3
"""
AptaSelect: Identifies high-frequency aptamer candidate sequences from
paired-end FASTQ files generated by SELEX experiments.

Stages:
  1. Join           – merge paired-end reads via overlapping region
  2. Selection      – filter by broad library structure (SEL_READ1/2)
  3. 1st Sort       – intermediate structural filter (S1_READ1/2, S1_LENGTH)
  4. 2nd Sort       – stringent core-region filter  (S2_READ1/2, S2_LENGTH)
  5. Aggregation    – sum counts across parallel chunks, rank, output top-N
"""

import sys
import gzip
import argparse
from collections import defaultdict
from multiprocessing import Pool


# ─── Utility ──────────────────────────────────────────────────────────────────

def reverse_complement(seq: str) -> str:
    comp = str.maketrans("ACGTacgt", "TGCAtgca")
    return seq.translate(comp)[::-1]


def hamming(a: str, b: str) -> int:
    return sum(x != y for x, y in zip(a, b))


def find_pattern(seq: str, pattern: str, max_mm: int, start: int = 0) -> int:
    """Leftmost position of pattern in seq[start:] with ≤ max_mm mismatches, else -1."""
    plen = len(pattern)
    for i in range(start, len(seq) - plen + 1):
        if hamming(seq[i : i + plen], pattern) <= max_mm:
            return i
    return -1


# ─── Stage 1: Join ────────────────────────────────────────────────────────────

def join_reads(seq1: str, qual1: str, seq2: str, qual2: str,
               min_overlap: int, pct_diff: float):
    rc2     = reverse_complement(seq2)
    qual2r  = qual2[::-1]

    for ov in range(len(seq1), min_overlap - 1, -1):
        s1_tail = seq1[-ov:]
        s2_head = rc2[:ov]
        mm      = hamming(s1_tail, s2_head)
        if mm / ov <= pct_diff / 100:
            pos = len(seq1) - ov
            # resolve mismatches using higher Phred quality
            merged = []
            for k in range(ov):
                b1, b2 = seq1[pos + k], rc2[k]
                if b1 == b2:
                    merged.append(b1)
                else:
                    q1 = ord(qual1[pos + k]) - 33
                    q2 = ord(qual2r[k])      - 33
                    merged.append(b1 if q1 >= q2 else b2)
            return seq1[:pos] + "".join(merged) + rc2[ov:]
    return None


# ─── Stages 2-4: Pattern filters ─────────────────────────────────────────────

def filter_between(seq: str, r1: str, r2: str, max_mm: int,
                   required_len: int = -1):
    """
    Find r1 then r2 downstream; extract the region between them.
    If required_len >= 0 the between region must be exactly that length.
    Returns the between-sequence or None on failure.
    """
    p1 = find_pattern(seq, r1, max_mm)
    if p1 == -1:
        return None
    p2 = find_pattern(seq, r2, max_mm, p1 + len(r1))
    if p2 == -1:
        return None
    between = seq[p1 + len(r1) : p2]
    if required_len >= 0 and len(between) != required_len:
        return None
    return between


# ─── Chunk processing (parallel worker) ──────────────────────────────────────

def process_chunk(args):
    (pairs,
     min_overlap, pct_diff,
     sel_r1, sel_r2,
     s1_r1, s1_r2, s1_len,
     s2_r1, s2_r2, s2_len,
     max_mm) = args

    counts: dict = defaultdict(int)

    for seq1, qual1, seq2, qual2 in pairs:
        joined = join_reads(seq1, qual1, seq2, qual2, min_overlap, pct_diff)
        if joined is None:
            continue

        sel = filter_between(joined, sel_r1, sel_r2, max_mm)
        if sel is None:
            continue

        s1 = filter_between(sel, s1_r1, s1_r2, max_mm, s1_len)
        if s1 is None:
            continue

        s2 = filter_between(s1, s2_r1, s2_r2, max_mm, s2_len)
        if s2 is None:
            continue

        counts[s2] += 1

    return counts


# ─── FASTQ reader ─────────────────────────────────────────────────────────────

def open_fastq(path: str):
    return gzip.open(path, "rt") if path.endswith(".gz") else open(path)


def read_paired_fastq(fq1: str, fq2: str, chunk_size: int):
    with open_fastq(fq1) as f1, open_fastq(fq2) as f2:
        while True:
            pairs = []
            for _ in range(chunk_size):
                h1 = f1.readline()
                if not h1:
                    break
                seq1  = f1.readline().strip()
                f1.readline()                     # '+'
                qual1 = f1.readline().strip()

                f2.readline()
                seq2  = f2.readline().strip()
                f2.readline()
                qual2 = f2.readline().strip()

                if seq1 and seq2:
                    pairs.append((seq1, qual1, seq2, qual2))
            if not pairs:
                break
            yield pairs


# ─── Main ─────────────────────────────────────────────────────────────────────

def main():
    ap = argparse.ArgumentParser(description="AptaSelect aptamer pipeline")
    ap.add_argument("--fastq1",         required=True)
    ap.add_argument("--fastq2",         required=True)
    ap.add_argument("--output",         required=True)
    ap.add_argument("--min_overlap",    type=int,   default=6)
    ap.add_argument("--pct_diff",       type=float, default=8.0)
    ap.add_argument("--sel_read1",      default="CCACTTCTCCTTCCATCCTAAAC")
    ap.add_argument("--sel_read2",      default="GAGTAGTTTGGAGGGTTGTCTG")
    ap.add_argument("--s1_read1",       default="TCCTAAAC")
    ap.add_argument("--s1_read2",       default="GAGTAGTT")
    ap.add_argument("--s1_length",      type=int,   default=40)
    ap.add_argument("--s2_read1",       default="TCTCTCTCTC")
    ap.add_argument("--s2_read2",       default="GAGAGAGAGA")
    ap.add_argument("--s2_length",      type=int,   default=20)
    ap.add_argument("--max_mismatches", type=int,   default=1)
    ap.add_argument("--top_n",          type=int,   default=10)
    ap.add_argument("--chunk_size",     type=int,   default=10000)
    ap.add_argument("--threads",        type=int,   default=4)
    args = ap.parse_args()

    # Build chunk argument list
    chunk_args = [
        (pairs,
         args.min_overlap, args.pct_diff,
         args.sel_read1, args.sel_read2,
         args.s1_read1,  args.s1_read2, args.s1_length,
         args.s2_read1,  args.s2_read2, args.s2_length,
         args.max_mismatches)
        for pairs in read_paired_fastq(args.fastq1, args.fastq2, args.chunk_size)
    ]

    # Stage 5: Aggregate
    global_counts: dict = defaultdict(int)
    with Pool(processes=args.threads) as pool:
        for chunk_counts in pool.imap_unordered(process_chunk, chunk_args):
            for seq, cnt in chunk_counts.items():
                global_counts[seq] += cnt

    ranked = sorted(global_counts.items(), key=lambda x: x[1], reverse=True)

    with open(args.output, "w") as out:
        out.write("rank\tsequence\tcount\n")
        for rank, (seq, cnt) in enumerate(ranked[: args.top_n], 1):
            out.write(f"{rank}\t{seq}\t{cnt}\n")

    total_unique = len(global_counts)
    print(f"Done. Unique candidates: {total_unique}. "
          f"Top {args.top_n} written to {args.output}.")


if __name__ == "__main__":
    main()